### ISSUE TITLE
Use private flag for requiring login

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-security#29]
Currently the private flag is all-or-nothing, so can't be activated on a per-site basis.

We can instead use the private flag of the site, which is how our other solutions for this work. Upstream issue at https://github.com/humanmade/hm-require-login/issues/5

**Comment by joehoyle** [comment]
Hey folks, I’m looking at https://github.com/humanmade/altis-security/pull/33/files which looks to make it so sites in dev / staging will not have require-login by default, or is the public option overridden somehow to provide that functionality?

**Comment by joehoyle** [comment]
Assuming the above is true, this means v3+ would have switched the default so previously private staging / dev sites that required login, no longer require so. However, I might be missing something there -- did we change / override the public setting maybe, so that is default private on staging / dev?

**Comment by roborourke** [comment]
This has been fixed and backported to v3.
