### ISSUE TITLE
Styling issues on Force 2FA Screen

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-security#38]
1. `Generate Verification Codes` and `Register New Key` links are overlapping each other in the top-right of the screen.

![Screenshot 2019-11-19 at 16 41 27](https://user-images.githubusercontent.com/5014023/69166950-fe675a80-0aeb-11ea-86c5-bbadcd07a54e.png)

2. The `Logout` link is obscured by the Query Monitor bar.

![Screenshot 2019-11-19 at 16 41 33](https://user-images.githubusercontent.com/5014023/69166993-10e19400-0aec-11ea-8516-9a61c8ada694.png)

----------

Acceptance criteria:

- [ ] The links in the top right are no longer overlapping but side by side
- [ ] On the login screen when query monitor is active add bottom padding to the body, logout link should not be obscured

**Comment by roborourke** [comment]
For 2. what exactly is happening? Is QM panel dragged down to be as short as possible? Guess we could add padding but you could also just close QM. For context it's only really going to be devs using QM, regular users will likely never encounter that. That said I prefer some extra bottom padding screens like this so that small but highly relevant links aren't seen as ignorable footer content.

**Comment by sambulance** [comment]
Yes, the QM bar is in minimised mode, and clicking the 'x' on the right didn't do anything because it's already minimised. You'd only see this on screens where the content is longer than the window height.

**Comment by jazzsequence** [comment]
The first issue is no longer an issue because `Generate Verification Codes` and `Register New Key` have been turned into buttons and no longer placed at the top right of the page.

The second issue is dependent upon the viewport and desktop resolution, but either way, it can be worked around by clicking on the ![Screen Shot 2021-01-18 at 2 20 04 PM](https://user-images.githubusercontent.com/991511/104963703-5c196000-5998-11eb-8963-3e0f175e9392.png) icon and moving the QM panel to the side of the screen instead. This is an edge case that requires a user to _already be logged in_ when the change to Force 2FA was made.

![Screen Shot 2021-01-18 at 2.17.35 PM.png](https://images.zenhubusercontent.com/5806695a95e42b6c5baaac94/e07a3da8-df6b-48d0-8f55-5fc8d87a767e)

I propose we close as `wontfix` since the larger issue is resolved and the other issue can be worked around in the rare occasions it may come up. cc @roborourke @PriyaBhatia0210 @jennybeaumont

**Comment by roborourke** [comment]
Yeah it's not been a priority really, nice one for finding the workaround. I'll close it out.
