### ISSUE TITLE
Impossible to disable require-login for non-public sites

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-security#92]
It's impossible to disable require-login on a non-public site. This means it's not possible to have a site that is publicly accessible but blocked to search engines, because it will always require visitors to be logged in to access it.

Related docs: https://docs.altis-dxp.com/security/require-login/#overrides

Steps to reproduce:
1. Put config in place to disable `require-login`:
	```
	"modules": {
		"security": {
			"require-login": false
		}
	}
	```
2. From the Settings -> Reading menu, check the `Discourage search engines from indexing this site` checkbox
3. Try to access the site when you're not logged in
4. Observe that you're redirected to the login screen despite `require-login` being false

Problem code:

* https://github.com/humanmade/altis-security/blob/700050bdee6e8a4f31b1c5213b768e8f72a13b34/inc/namespace.php#L39-L41
* https://github.com/humanmade/altis-security/blob/700050bdee6e8a4f31b1c5213b768e8f72a13b34/inc/namespace.php#L79-L84

**Comment by roborourke** [comment]
This behaviour was intentional as a means of being to have individual private sites on the network. It's unfortunate that WP syncs and treats the "public" setting the same as "discourage search engines". Arguably a site that isn't public shouldn't be publicly accessible hence the current implementation decided on in https://github.com/humanmade/altis-security/issues/29

Apologies for misreporting the intended behaviour to you.

I think ultimately the best solution will to work out a way to split those settings from one another, or to relabel the "discourage search engines" field and add a new one that controls the output of `robots.txt` or robots meta tags.

**Comment by rmccue** [comment]
Closing as intentional.
